### ISSUE TITLE
How to crop from the center of an image

### ISSUE THREAD

**Issue by bertoost** [PHPixie/Image#4]
First; great library! Very easy to use.

I almost got my goal;
What I want to achieve is a cropped 200x200 image, cropped from the center.
I now have;

```
$phpixie
    ->read($filePath)
    ->resize(200, 150, false)
    ->crop(200, 150)
    ->save(THUMBS_PATH . $uniqueName . '.jpg', 'jpg', 80);
```

I tried to get the new size between `resize()` and `crop()` but didn't get that to work. Can you give me some directions? :-)

Thanks in advance.

Regards, Bert

**Comment by dracony** [comment]
Sorry, I missed this issue originally. Did you find a solution? I assume so by now. But I will add an update to the docs.
